//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Menu
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BD_MenuEntities1 : DbContext
    {
        public BD_MenuEntities1()
            : base("name=BD_MenuEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Class> Classes { get; set; }
        public virtual DbSet<ClassMenu> ClassMenus { get; set; }
        public virtual DbSet<Dish> Dishes { get; set; }
        public virtual DbSet<DishMealTime> DishMealTimes { get; set; }
        public virtual DbSet<MealTime> MealTimes { get; set; }
        public virtual DbSet<Norm> Norms { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
